name: Deploy
on:
  push:
    branches: [ main, rc-stage ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      #- name: Update npm
      #  run: npm install -g npm@latest # ensure npm 11.5.1 or later
      - name: Setup Google Chrome v149 # WATCH: match with axe-cli prerequisites
        uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # 2.1.2
        id: setup-chrome
        with:
          chrome-version: '149'
          install-dependencies: true
          install-chromedriver: true
      - name: Export Chrome Binary Paths
        run: |
          echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=${{ steps.setup-chrome.outputs.chromedriver-path }}" >> $GITHUB_ENV
      - run: npm ci
      - run: npx playwright install
      - name: Verify
        run: |
          npm run lint
          npm run test:ci
          npm run test:playwright
      - name: Publish
        run: |
          if [ "${{ github.ref_name }}" = "rc-stage" ]; then
            npm publish --access public --tag rc
          else
            npm publish --access public
          fi